services:
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  worker:
    build:
      context: .
      dockerfile: Dockerfile
    command: celery -A backend worker --pool=solo -l info
    volumes:
      - .:/app
    depends_on:
      - redis

  beat:
    build:
      context: .
      dockerfile: Dockerfile
    command: celery -A backend beat -l info
    volumes:
      - .:/app
    depends_on:
      - redis

volumes:
  redis_data: