# Generated by Django 5.2.1 on 2025-05-07 22:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='QRCodeLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('qr_code', models.ImageField(blank=True, upload_to='qr_codes/')),
                ('seat', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='dashboard.seat')),
            ],
        ),
    ]
